Repository loopbackio/loopback-datasource-juggler, pull requests merged in 2018-04, with the labels that each got.

#1532 feat: omit default fn for embedsMany
  lib/relation-definition.js
  test/relations.test.js
Labels: needs-priority

#1573 feat: remove a Model from all registries
  lib/datasource.js
  lib/model-builder.js
  test/datasource.test.js
Labels: #review, customer, feature

#1575 Polyfill Number.isFinite() to support PhantomJS
  lib/utils.js
Labels: #review
