Repository loopbackio/loopback-datasource-juggler, pull requests merged in 2019-04, with the labels that each got.

#1704 fix: do not apply default values on data from database
  lib/dao.js
  test/basic-querying.test.js
  test/defaults.test.js
  test/manipulation.test.js
Labels: bug, customer, major

#1706 Do not apply default values on data from database [2.x]
  lib/dao.js
  test/basic-querying.test.js
  test/manipulation.test.js
Labels: bug, customer

#1581 fix: normalize include with boolean or number
  lib/include.js
  test/include.test.js
Labels: bug, community-contribution

#1717 fix: normalize include with boolean or number [3.x]
  lib/include.js
  test/include.test.js
Labels: bug, community-contribution

#1718 fix: normalize include with boolean or number [2.x]
  lib/include.js
  test/include.test.js
Labels: bug, community-contribution

#1702 fix: nested property coercion and resolution
  lib/dao.js
  lib/list.js
  test/basic-querying.test.js
  test/datatype.test.js
  test/manipulation.test.js
Labels: customer
