Repository loopbackio/loopback-datasource-juggler, pull requests merged in 2019-07, with the labels that each got.

#1756 fix: report errors from automigrate/autoupdate
  lib/datasource.js
  test/datasource.test.js
Labels: bug

#1759 feat: add DataSource.deleteAllModels() API
  lib/datasource.js
  test/datasource.test.js
  types/datasource.d.ts
Labels: feature

#1762 Fix autoupdate queueing automigrate instead
  lib/datasource.js
Labels: community-contribution

#1763 Fix coercion of PK value in `replaceById` method
  lib/dao.js
  test/manipulation.test.js
Labels: bug
