Repository loopbackio/loopback-datasource-juggler, pull requests merged in 2019-11, with the labels that each got.

#1783 Fix issue with lb4 id different to int
  lib/datasource.js
  test/loopback-dl.test.js
  test/manipulation.test.js
Labels: community-contribution

#1797 feat: support applyDefaultOnWrites in nested properties
  lib/model.js
  test/defaults.test.js
Labels: customer

#1790 Convert error from a property setter to a rejected promise
  lib/dao.js
  test/manipulation.test.js
Labels: bug, community-contribution
