Repository loopbackio/loopback-datasource-juggler, pull requests merged in 2019-01, with the labels that each got.

#1682 fix: use existing field in exclude test
  test/include.test.js
Labels: interrupt

#1685 Improve Model type definitions
  types/model.d.ts
Labels: feature

#1670 Enable to target ES6
  lib/model-builder.js
  lib/model-utils.js
  lib/utils.js
  test/datatype.test.js
  test/model-builder.test.js
Labels: bug, community-contribution
