Repository loopbackio/loopback-datasource-juggler, pull requests merged in 2019-12, with the labels that each got.

#1800 Return rejected promise on error [3.x]
  lib/dao.js
  test/manipulation.test.js
Labels: bug, community-contribution

#1807 Fix Promise/Callback variants in datasource types
  types/datasource.d.ts
Labels: developer-experience

#1799 Fix issue with broken compatibility with array constructor
  lib/list.js
  test/list.test.js
Labels: bug, community-contribution

#1805 fix(security): avoid prototype pollution on model create and update
  lib/dao.js
  lib/model.js
  lib/utils.js
  test/default-scope.test.js
Labels: community-contribution

#1813 feat: added persistDefaultValues
  lib/model.js
  test/defaults.test.js
Labels: customer

#1815 feat: added persistDefaultValues 3.x
  lib/model.js
  test/defaults.test.js
Labels: customer
